name: TCGstorageAPI build

on:
  push:
    branches:
      - Python2.7

jobs:
  build:
    name: TCGstorageAPI_build
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout git submodules
        run: git submodule update --init --recursive 
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install python2.7-minimal
          sudo apt install python-pip
          sudo apt-get install -y --no-install-recommends python-all python-all-dev
          sudo apt-get install libgnutls28-dev
          sudo apt-get install libboost-all-dev
      - name: Install python requirement packages
        run: |
          sudo apt-get install python-setuptools
          pip install --no-cache-dir -r requirements.txt
      - name: Build opensea
        run: python setup.py opensea
      - name: Build TCGstorageAPI package
        run: python setup.py build
        
